name: Docker Self Stable

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

env:
    REGISTRY: registry.cn-shanghai.aliyuncs.com
    IMAGE_NAME: ideaU
    ALIYUN: xmtang/idea_u
    PROJECTOR_STABLE: v1.7.0
    IMAGE_TAG: v1.0 # 用于标记容器版本号

jobs:
    build-ideaU:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
                with:
                    path: projector-docker

            -   name: Checkout server repo
                uses: actions/checkout@v2
                with:
                    repository: JetBrains/projector-server
                    path: projector/projector-server
                    ref: refs/tags/${{ env.PROJECTOR_STABLE }}

            -   name: Login to Aliyun Container Registry (ACR)
                uses: aliyun/acr-login@v1 # 使用阿里云镜像服务action
                with:
                    login-server: ${{ env.REGISTRY }} # 务必正确填写镜像容器服务的登录地址
                    region-id: cn-shanghai # 务必正确填写镜像容器服务的登录地址
                    username: ${{ secrets.Aliyun_Username }} # 引用GitHub repo设置的镜像容器服务用户名
                    password: ${{ secrets.Aliyun_Password }} # 引用GitHub repo设置的镜像容器服务密码
            -   name: Build and Push Docker Image

                # docker build -t ${{ env.REGISTRY }}/$ALIYUN:$IMAGE_TAG .
                run: |
                    ls -lh
                    cd projector-docker
                    docker build --progress=plain -t ${{ env.REGISTRY }}/${{ env.$ALIYUN }}:${{ env.$IMAGE_TAG }} --build-arg buildGradle=true --build-arg "downloadUrl=$downloadUrl" -f Dockerfile ..
                    docker push ${{ env.REGISTRY }}/${{ env.$ALIYUN }}:${{ env.$IMAGE_TAG }}
